default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:

development:
  <<: *default
  database: rails_capistrano_development

staging:
  <<: *default
  database: rails_capistrano_staging
  username: root
  password:
  host: localhost
